POST http://localhost:8080/subscribe
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
data: jsonString

{"email": "student@haw-landshut.de", "password": "password", "classRoomName": "Hardware Software Codesign"}

###